# Generated by Django 3.2.4 on 2021-07-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_message_messageattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ('created_at',)},
        ),
    ]
